class CarryOutDueDiligenceOnPreferredSupportingOrganisation {

}

const carryOutDueDiligenceOnPreferredSupportingOrganisation = new CarryOutDueDiligenceOnPreferredSupportingOrganisation();

export default carryOutDueDiligenceOnPreferredSupportingOrganisation;